-------------------------------------------------------------------------------
Test set: models.EndangeredAnimalTest
-------------------------------------------------------------------------------
Tests run: 7, Failures: 0, Errors: 5, Skipped: 0, Time elapsed: 4.483 sec <<< FAILURE! - in models.EndangeredAnimalTest
all_returnsAllInstancesOfEndangeredAnimal_true(models.EndangeredAnimalTest)  Time elapsed: 1.579 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: no pg_hba.conf entry for host "102.167.90.70", user "aaxdbnmafohegw", database "dftdbh9698l7s0", SSL off
	at models.EndangeredAnimalTest.all_returnsAllInstancesOfEndangeredAnimal_true(EndangeredAnimalTest.java:30)
Caused by: org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "102.167.90.70", user "aaxdbnmafohegw", database "dftdbh9698l7s0", SSL off
	at models.EndangeredAnimalTest.all_returnsAllInstancesOfEndangeredAnimal_true(EndangeredAnimalTest.java:30)

update_updatesAgeAttribute_true(models.EndangeredAnimalTest)  Time elapsed: 0.821 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: no pg_hba.conf entry for host "102.167.90.70", user "aaxdbnmafohegw", database "dftdbh9698l7s0", SSL off
	at models.EndangeredAnimalTest.update_updatesAgeAttribute_true(EndangeredAnimalTest.java:57)
Caused by: org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "102.167.90.70", user "aaxdbnmafohegw", database "dftdbh9698l7s0", SSL off
	at models.EndangeredAnimalTest.update_updatesAgeAttribute_true(EndangeredAnimalTest.java:57)

save_assignsIdAndSavesObjectToDatabase(models.EndangeredAnimalTest)  Time elapsed: 0.585 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: no pg_hba.conf entry for host "102.167.90.70", user "aaxdbnmafohegw", database "dftdbh9698l7s0", SSL off
	at models.EndangeredAnimalTest.save_assignsIdAndSavesObjectToDatabase(EndangeredAnimalTest.java:22)
Caused by: org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "102.167.90.70", user "aaxdbnmafohegw", database "dftdbh9698l7s0", SSL off
	at models.EndangeredAnimalTest.save_assignsIdAndSavesObjectToDatabase(EndangeredAnimalTest.java:22)

find_returnsAnimalWithSameId_secondAnimal(models.EndangeredAnimalTest)  Time elapsed: 0.82 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: no pg_hba.conf entry for host "102.167.90.70", user "aaxdbnmafohegw", database "dftdbh9698l7s0", SSL off
	at models.EndangeredAnimalTest.find_returnsAnimalWithSameId_secondAnimal(EndangeredAnimalTest.java:40)
Caused by: org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "102.167.90.70", user "aaxdbnmafohegw", database "dftdbh9698l7s0", SSL off
	at models.EndangeredAnimalTest.find_returnsAnimalWithSameId_secondAnimal(EndangeredAnimalTest.java:40)

update_updatesHealthAttribute_true(models.EndangeredAnimalTest)  Time elapsed: 0.612 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: no pg_hba.conf entry for host "102.167.90.70", user "aaxdbnmafohegw", database "dftdbh9698l7s0", SSL off
	at models.EndangeredAnimalTest.update_updatesHealthAttribute_true(EndangeredAnimalTest.java:49)
Caused by: org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "102.167.90.70", user "aaxdbnmafohegw", database "dftdbh9698l7s0", SSL off
	at models.EndangeredAnimalTest.update_updatesHealthAttribute_true(EndangeredAnimalTest.java:49)

